### PR TITLE
are some changes to the definition of left fold in this table called for?

### PR DESCRIPTION
**Pull request by philipschwarz**
Hey Sergei,

How are you doing (looking after a kid and writing a book at the same time must be a lot of work!) ?

See the image below for what I am thinking about (click on slide to enlarge).

image

What do you think?

### CODE REVIEW

**Comment by philipschwarz** [comment]
If the above is right, then maybe the table could contain both the left fold and the right fold (click on image to enlarge):

image

**Comment by winitzki** [comment]
Hi Philip,

thank you for your comments. I will have to think about this some more. It could be one thing how `foldLeft` or `foldl` are defined, and another how we write the result as a formula. I did not talk about the difference between left and right folds because I feel that these differences are not essential. Let us forget about `List` being a recursively defined type, and just think of folding over a finite array. Then we certainly don't care much about distinctions between left and right folding, it's all a matter of convenience. 
But it is important to not confuse readers with definitions that conflict with other sources.

Sergei

**Comment by philipschwarz** [comment]
>thank you for your comments

thanks for taking the time to look at this

>I will have to think about this some more.

of course - this is also just a small topic amongst all the many and more important ones in the rest of the book

> I did not talk about the difference between left and right folds because I feel that these differences are not essential. 

yes, I noticed that you have been quite deliberate in doing that

>we certainly don't care much about distinctions between left and right folding, it's all a matter of convenience.

Yes, we spoke, in a previous PR, about how in Scala, foldRight is defined in terms of foldLeft! [see here](https://github.com/scala/scala/commit/6db4db9) 
Also, probably not many developers have to deal with real-world scenarios that are the equivalent of toy scenarios like the difference between a left fold and a right fold with subtraction:

```Scala
scala> List(1,2,3).foldLeft(0)(_-_)
val res0: Int = -6

scala> List(1,2,3).foldRight(0)(_-_)                                                     
val res1: Int = 2
```

>But it is important to not confuse readers with definitions that conflict with other sources.

Yes. 

There is more than one reason why I have contacted you about it. One is that I have been very interested in the subject of folding, so it is easy for me to get carried away. But the other is that the first time I saw your table, I just scanned the first row and said to myself, what is this? Interesting, he is describing folding mathematically in a slightly different way to the ones I had come across. That feels strange. But wait, no, he has his mathematician's hat on, he is concentrating on what matters in this book and actually doing a good job of conveying the essence of what folding (and unfolding, scanning) are. So I warmed to the notation and I could then see the value. But then I looked at the definitions more, and when it came to the first one, the one for fold, I found that if I look at it one way, it is almost describing a right fold, which is what you have been avoiding to talk about too much in your book. So I thought you might be interested in replacing the current mathematical definition with the one that I had a go at coming up with, which is for a left fold, so as not to confuse people (because the Scala code in that row is for a left fold). 

I am arguing that if the Scala snippet uses foldLeft, then the definition I have proposed (if you think it is correct) could replace the existing one, but given the approach you took in the book, I wouldn't be surprised if you stuck to the existing definition, explaining why in your view it is generic, not about left or right fold, or if you came up with a new definition that satisfies that criterion.  

In the end, all that matters is that if there is scope for improvement then we improve the book. There may well not be. 

Thanks for reading this,

Philip

**Comment by winitzki** [comment]
The definition `f(y_k, []) = y_k, f(y_k, x ++ xs) = f(...)` is just a tail-recursive definition of a `foldLeft` with an accumulator argument. I'd like to avoid putting tail recursion into a mathematical formula, because tail recursion is just a detail of how we implement this function. This said, I'll still have to take a look at possibly how to write the formula in a better way.

**Comment by philipschwarz** [comment]
> The definition f(y_k, []) = y_k, f(y_k, x ++ xs) = f(...) is just a tail-recursive definition of a foldLeft with an accumulator argument. 
Yes, that is exactly what it is.

> I'd like to avoid putting tail recursion into a mathematical formula, because tail recursion is just a detail of how we implement this function.

Right, I saw the use of recursion in the existing mathematical definition of fold in the table and concluded that you considered it acceptable, so I took it as a rule of the game and thought it would be just as acceptable in a replacement definition that reflects a left fold rather than reflecting (nearly) a right fold. 

>  I'll still have to take a look at possibly how to write the formula in a better way.

Cool

>Perhaps I'll just add a line with foldRight and a comment that the difference is not essential at this point.

so, correct me if I misunderstand: you might have a line for foldLeft and one for foldRight, but as you say, you would stress the point that the difference is not essential in the context of the book - makes sense

> To me, the important point is that "folding" is a sequence-to-value ("aggregation") while "unfolding" and "scanning" are value-to-sequence and sequence-to-sequence transformations.

Yes, that is clear

> Now you could say exactly the same about unfolding and scanning; you could have unfoldLeft, unfoldRight and so on. 

Yes, in fact I had thought about it for scanning, but did not want to bring it up too early. I hadn't thought about that for unfolding.



> Maybe they are useful in some contexts.

Yes

Toy example:

```Scala
scala> List(1,2,3).scanLeft(0)(_-_)                                                      
val res2: List[Int] = List(0, -1, -3, -6)

scala> List(1,2,3).scanRight(0)(_-_)                                                     
val res3: List[Int] = List(2, -1, 3, 0)

scala> 
```

**Comment by winitzki** [comment]
For unfolding, you might have sequences that "grow to the right" or sequences that "grow to the left". Apart from implementation, there is no real difference.

**Comment by winitzki** [comment]
Hi Philip,
Sorry for a long delay. I made a PR to add `foldRight` to the table.
https://github.com/winitzki/sofp/pull/40

Screen Shot 2021-06-25 at 5 37 45 PM

The definitions of `foldRight` and `foldLeft` are quite similar. I believe they are correct (and the same in Haskell and in Scala). For instance, `foldRight` has an argument of type `A => B => B` while `foldLeft` has an argument of type `B => A => B`. Accordingly, the mathematical formula has `g(x, f(s))` or `g(f(s), x)`. But there is no other difference. The fact that `foldLeft` is tail-recursive for `List` is an implementation detail that is specific to the `List` type. It will be different for other sequence types. I do not want to put the implementation details into the formulas.

So I'm suggesting to close this PR.

**Comment by philipschwarz** [comment]
> Sorry for a long delay.
Not at all, I am sure you are very busy

So you have added a new row for foldRight:
image

Let me check:
IMG_5937

Yes, that checks out. Your original definition of f for foldLeft is actually fine, and I see that the new definition of f for foldRight is exactly how I said I imagined it would be. I agree that, given the approach you are taking in the book, it is undesirable to let the implementation detail of tail-recursion leak into the definition of f for foldLeft (which is what my proposed definition of f for foldLeft suffers from). 

So you end up with something nice and simple. Great!

> So I'm suggesting to close this PR.
Yep, makes sense.

Thanks,

Philip

**Comment by winitzki** [comment]
Closing in favor of https://github.com/winitzki/sofp/pull/40

**Pull request closed without merging**
