### PR TITLE
#82, Missing condition in 1.6.2.3, fixed

### PR DESCRIPTION
**Pull request by andreas-roehler**

### CODE REVIEW

**Comment by winitzki** [comment]
One problem with PRs for LyX files is that it's hard to understand the change by looking at the PR. It is also hard to respond to the change; say, I can load the PR branch into the LyX editor, but if I want to suggest some changes, it's hard to figure out what lines in the PR need to be modified.

**Comment by andreas-roehler** [comment]
Probably the easiest is not to use the PR and just make your edits. Will survive it ;) Or just take it followed by another edit.

**Comment by winitzki** [comment]
It is best if you just describe your change in words: "old text is ... and new text is ..."
I will then make changes as needed.

**Comment by andreas-roehler** [comment]
Old:

if there are only three different integers j ∈ [1, ..., n]

New:

if there are only three different integers i,j,k ∈ [1, ..., n] and 1 < i,j,k < n

**Comment by winitzki** [comment]
I have made the changes, thank you.

**Pull request closed without merging**
